### ISSUE TITLE
Nextflux causes high resources consumption of the Miniflux

### ISSUE THREAD

**Issue by dmlogv** [electh/nextflux#47]
Thank you for the Nextflux.

I've set it up, and Nextflux tends to made Miniflux feel sick. Actually, I have read yet any post using it :)

My compose:

```yaml
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    ports:
      - '8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - HTTP_CLIENT_PROXY=***
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped
    labels:
      - reproxy.server=rss***
      - reproxy.route=^/(.*)
      - reproxy.dest=/@1
      - reproxy.port=8080

  db:
    image: postgres:14
    container_name: miniflux_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $MINIFLUX_DATA/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped
    labels:
      - reproxy.exclude=true

  nextflux:
    image: electh/nextflux:latest
    container_name: nextflux
    ports:
      - '80'
    depends_on:
      - miniflux
    restart: unless-stopped
    labels:
      - reproxy.server=nextflux***
      - reproxy.route=^/(.*)
      - reproxy.dest=/@1
      - reproxy.port=80
      
networks:
  default:
    name: reproxy
    external: true   
```

After starting everything looks fine, but when I try to refresh feeds, Miniflux stars to heat up my home lab:

```
CONTAINER ID   NAME                      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
216247ba05f9   miniflux                  114.47%   3.258GiB / 7.653GiB   42.57%    512MB / 22.9MB    30.9MB / 180MB    11
60826cb84341   nextflux                  0.00%     3.453MiB / 2GiB       0.17%     61.6kB / 4.73kB   905kB / 4.1kB     3
fdc812f0aac0   miniflux_db               15.28%    657.4MiB / 2GiB       32.10%    18.6MB / 636MB    533MB / 2.33GB    19
```

Nextflux logs:

```
nextflux  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nextflux  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
nextflux  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nextflux  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nextflux  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nextflux  | /docker-entrypoint.sh: Configuration complete; ready for start up
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: using the "epoll" event method
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: nginx/1.27.3
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: OS: Linux 6.1.0-29-amd64
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: start worker processes
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: start worker process 29
nextflux  | 2025/01/22 13:06:02 [notice] 1#1: start worker process 30
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:10:29 +0000] "GET /feed/114 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:10:29 +0000] "GET /feed/site.webmanifest HTTP/1.1" 200 1655 "https://nextflux.***/feed/114" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:12:59 +0000] "GET /feed/114 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:12:59 +0000] "GET /feed/site.webmanifest HTTP/1.1" 200 1655 "https://nextflux.***/feed/114" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:25:06 +0000] "GET /feed/114 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
nextflux  | 172.19.0.3 - - [22/Jan/2025:13:25:06 +0000] "GET /feed/site.webmanifest HTTP/1.1" 200 1655 "https://nextflux.***/feed/114" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15" "192.168.80.131"
```

Safari's JS console:

```
[Warning] Parsing application manifest : The manifest is not valid JSON data.
[Log] 执行同步 (index-BUb-PH_i.js, line 465)
[Log] 启动后台刷新，间隔： – 5 – "分钟" (index-BUb-PH_i.js, line 465)
[Error] Failed to load resource: the server responded with a status of 404 () (faviconV2, line 0)
...
[Error] Origin https://nextflux.*** is not allowed by Access-Control-Allow-Origin. Status code: 502
[Error] XMLHttpRequest cannot load https://rss.***/v1/entries?status=unread&direction=desc&limit=0 due to access control checks.
[Error] 同步文章失败: – Zt {stack: "@https://nextflux.***/assets/index-BUb-P…x.***/assets/index-BUb-PH_i.js:464:2079", message: "Network Error", name: "AxiosError", …}
Zt {stack: "@https://nextflux.***/assets/index-BUb-P…x.***/assets/index-BUb-PH_i.js:464:2079", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: Object, …}Zt
  (anonymous function) (index-BUb-PH_i.js:465:7749)
[Error] Failed to load resource: Origin https://nextflux.*** is not allowed by Access-Control-Allow-Origin. Status code: 502 (entries, line 0)
```

NB: Miniflux holds 160 feeds.

I'm not sure that it's Nextflux issue, but I hope you can help me to determine the problem.
